In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("../data/tx_npidata.csv")

C:\Users\Bapan Bairagya\AppData\Local\Temp\ipykernel_4436\1142504934.py:1: DtypeWarning: Columns (17,32,39,40,52,56,60,61,64,65,68,69,72,73,76,77,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,111,113,114,115,117,118,119,121,122,123,125,126,127,129,130,131,133,134,135,137,138,139,141,142,143,145,146,147,149,150,151,153,154,155,157,158,159,161,162,163,165,166,167,169,170,171,173,174,175,177,178,179,181,182,183,185,186,187,189,190,191,193,194,195,197,198,199,201,202,203,205,206,207,209,210,211,213,214,215,217,218,219,221,222,223,225,226,227,229,230,231,233,234,235,237,238,239,241,242,243,245,246,247,249,250,251,253,254,257,258,259,261,262,263,265,266,267,269,270,271,273,274,275,277,278,279,281,282,283,285,286,287,289,290,291,293,294,297,298,299,301,302,303,305,306,319,320,321,322,323,324,325,326,327,328) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/tx_npidata.csv")

In [3]:
# Convert the column to string using original name
df["Provider Business Practice Location Address Telephone Number"] = df["Provider Business Practice Location Address Telephone Number"].astype(str)

In [4]:
df.head(3)

,NPI,Entity Type Code,Replacement NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,Provider Other Organization Name,Provider Other Organization Name Type Code,Provider Other Last Name,Provider Other First Name,Provider Other Middle Name,Provider Other Name Prefix Text,Provider Other Name Suffix Text,Provider Other Credential Text,Provider Other Last Name Type Code,Provider First Line Business Mailing Address,Provider Second Line Business Mailing Address,Provider Business Mailing Address City Name,Provider Business Mailing Address State Name,Provider Business Mailing Address Postal Code,Provider Business Mailing Address Country Code (If outside U.S.),Provider Business Mailing Address Telephone Number,Provider Business Mailing Address Fax Number,Provider First Line Business Practice Location Address,Provider Second Line Business Practice Location Address,Provider Business Practice Location Address City Name,Provider Business Practice Location Address State Name,Provider Business Practice Location Address Postal Code,Provider Business Practice Location Address Country Code (If outside U.S.),Provider Business Practice Location Address Telephone Number,Provider Business Practice Location Address Fax Number,Provider Enumeration Date,Last Update Date,NPI Deactivation Reason Code,NPI Deactivation Date,NPI Reactivation Date,Provider Sex Code,Authorized Official Last Name,Authorized Official First Name,Authorized Official Middle Name,Authorized Official Title or Position,Authorized Official Telephone Number,Healthcare Provider Taxonomy Code_1,Provider License Number_1,Provider License Number State Code_1,Healthcare Provider Primary Taxonomy Switch_1,Healthcare Provider Taxonomy Code_2,Provider License Number_2,Provider License Number State Code_2,Healthcare Provider Primary Taxonomy Switch_2,Healthcare Provider Taxonomy Code_3,Provider License Number_3,Provider License Number State Code_3,Healthcare Provider Primary Taxonomy Switch_3,Healthcare Provider Taxonomy Code_4,Provider License Number_4,Provider License Number State Code_4,Healthcare Provider Primary Taxonomy Switch_4,Healthcare Provider Taxonomy Code_5,Provider License Number_5,Provider License Number State Code_5,Healthcare Provider Primary Taxonomy Switch_5,Healthcare Provider Taxonomy Code_6,Provider License Number_6,Provider License Number State Code_6,Healthcare Provider Primary Taxonomy Switch_6,Healthcare Provider Taxonomy Code_7,Provider License Number_7,Provider License Number State Code_7,Healthcare Provider Primary Taxonomy Switch_7,Healthcare Provider Taxonomy Code_8,Provider License Number_8,Provider License Number State Code_8,Healthcare Provider Primary Taxonomy Switch_8,Healthcare Provider Taxonomy Code_9,Provider License Number_9,Provider License Number State Code_9,Healthcare Provider Primary Taxonomy Switch_9,Healthcare Provider Taxonomy Code_10,Provider License Number_10,Provider License Number State Code_10,Healthcare Provider Primary Taxonomy Switch_10,Healthcare Provider Taxonomy Code_11,Provider License Number_11,Provider License Number State Code_11,Healthcare Provider Primary Taxonomy Switch_11,Healthcare Provider Taxonomy Code_12,Provider License Number_12,Provider License Number State Code_12,Healthcare Provider Primary Taxonomy Switch_12,Healthcare Provider Taxonomy Code_13,Provider License Number_13,Provider License Number State Code_13,Healthcare Provider Primary Taxonomy Switch_13,Healthcare Provider Taxonomy Code_14,Provider License Number_14,Provider License Number State Code_14,Healthcare Provider Primary Taxonomy Switch_14,Healthcare Provider Taxonomy Code_15,Provider License Number_15,Provider License Number State Code_15,Healthcare Provider Primary Taxonomy Switch_15,Other Provider Identifier_1,Other Provider Identifier Type Code_1,Other Provider Identifier State_1,Other Provider Identifier Issuer_1,Other Provider Identifier_2,Other Provider Identifier Type Code_2,Other Provider Identifier State_2,Other Provider Identifier Issuer_2,Other Provider Identifier_3,Other Provider Identifier Type Code_3,Other Provider Identifier State_3,Other Provider Identifier Issuer_3,Other Provider Identifier_4,Other Provider Identifier Type Code_4,Other Provider Identifier State_4,Other Provider Identifier Issuer_4,Other Provider Identifier_5,Other Provider Identifier Type Code_5,Other Provider Identifier State_5,Other Provider Identifier Issuer_5,Other Provider Identifier_6,Other Provider Identifier Type Code_6,Other Provider Identifier State_6,Other Provider Identifier Issuer_6,Other Provider Identifier_7,Other Provider Identifier Type Code_7,Other Provider Identifier State_7,Other Provider Identifier Issuer_7,Other Provider Identifier_8,Other Provider Identifier Type Code_8,Other Provider Identifier State_8,Other Provider Identifier Issuer_8,Other Provider Identifier_9,Other Provider Identifier Type Code_9,Other Provider Identifier State_9,Other Provider Identifier Issuer_9,Other Provider Identifier_10,Other Provider Identifier Type Code_10,Other Provider Identifier State_10,Other Provider Identifier Issuer_10,Other Provider Identifier_11,Other Provider Identifier Type Code_11,Other Provider Identifier State_11,Other Provider Identifier Issuer_11,Other Provider Identifier_12,Other Provider Identifier Type Code_12,Other Provider Identifier State_12,Other Provider Identifier Issuer_12,Other Provider Identifier_13,Other Provider Identifier Type Code_13,Other Provider Identifier State_13,Other Provider Identifier Issuer_13,Other Provider Identifier_14,Other Provider Identifier Type Code_14,Other Provider Identifier State_14,Other Provider Identifier Issuer_14,Other Provider Identifier_15,Other Provider Identifier Type Code_15,Other Provider Identifier State_15,Other Provider Identifier Issuer_15,Other Provider Identifier_16,Other Provider Identifier Type Code_16,Other Provider Identifier State_16,Other Provider Identifier Issuer_16,Other Provider Identifier_17,Other Provider Identifier Type Code_17,Other Provider Identifier State_17,Other Provider Identifier Issuer_17,Other Provider Identifier_18,Other Provider Identifier Type Code_18,Other Provider Identifier State_18,Other Provider Identifier Issuer_18,Other Provider Identifier_19,Other Provider Identifier Type Code_19,Other Provider Identifier State_19,Other Provider Identifier Issuer_19,Other Provider Identifier_20,Other Provider Identifier Type Code_20,Other Provider Identifier State_20,Other Provider Identifier Issuer_20,Other Provider Identifier_21,Other Provider Identifier Type Code_21,Other Provider Identifier State_21,Other Provider Identifier Issuer_21,Other Provider Identifier_22,Other Provider Identifier Type Code_22,Other Provider Identifier State_22,Other Provider Identifier Issuer_22,Other Provider Identifier_23,Other Provider Identifier Type Code_23,Other Provider Identifier State_23,Other Provider Identifier Issuer_23,Other Provider Identifier_24,Other Provider Identifier Type Code_24,Other Provider Identifier State_24,Other Provider Identifier Issuer_24,Other Provider Identifier_25,Other Provider Identifier Type Code_25,Other Provider Identifier State_25,Other Provider Identifier Issuer_25,Other Provider Identifier_26,Other Provider Identifier Type Code_26,Other Provider Identifier State_26,Other Provider Identifier Issuer_26,Other Provider Identifier_27,Other Provider Identifier Type Code_27,Other Provider Identifier State_27,Other Provider Identifier Issuer_27,Other Provider Identifier_28,Other Provider Identifier Type Code_28,Other Provider Identifier State_28,Other Provider Identifier Issuer_28,Other Provider Identifier_29,Other Provider Identifier Type Code_29,Other Provider Identifier State_29,Other Provider Identifier Issuer_29,Other Provider Identifier_30,Other Provider Identifier Type Code_30,Other Provider Identifier State_30,Other Provider Identifier Issuer_30,Other Provider Identifier_31,Other Provider Identifier Type Code_31,Other Provider Identifier State_31,Other Provider Identifier Issuer_31,Other Provider Identifier_32,Other Provider Identifier Type Code_32,Other Provider Identifier State_32,Other Provider Identifier Issuer_32,Other Provider Identifier_33,Other Provider Identifier Type Code_33,Other Provider Identifier State_33,Other Provider Identifier Issuer_33,Other Provider Identifier_34,Other Provider Identifier Type Code_34,Other Provider Identifier State_34,Other Provider Identifier Issuer_34,Other Provider Identifier_35,Other Provider Identifier Type Code_35,Other Provider Identifier State_35,Other Provider Identifier Issuer_35,Other Provider Identifier_36,Other Provider Identifier Type Code_36,Other Provider Identifier State_36,Other Provider Identifier Issuer_36,Other Provider Identifier_37,Other Provider Identifier Type Code_37,Other Provider Identifier State_37,Other Provider Identifier Issuer_37,Other Provider Identifier_38,Other Provider Identifier Type Code_38,Other Provider Identifier State_38,Other Provider Identifier Issuer_38,Other Provider Identifier_39,Other Provider Identifier Type Code_39,Other Provider Identifier State_39,Other Provider Identifier Issuer_39,Other Provider Identifier_40,Other Provider Identifier Type Code_40,Other Provider Identifier State_40,Other Provider Identifier Issuer_40,Other Provider Identifier_41,Other Provider Identifier Type Code_41,Other Provider Identifier State_41,Other Provider Identifier Issuer_41,Other Provider Identifier_42,Other Provider Identifier Type Code_42,Other Provider Identifier State_42,Other Provider Identifier Issuer_42,Other Provider Identifier_43,Other Provider Identifier Type Code_43,Other Provider Identifier State_43,Other Provider Identifier Issuer_43,Other Provider Identifier_44,Other Provider Identifier Type Code_44,Other Provider Identifier State_44,Other Provider Identifier Issuer_44,Other Provider Identifier_45,Other Provider Identifier Type Code_45,Other Provider Identifier State_45,Other Provider Identifier Issuer_45,Other Provider Identifier_46,Other Provider Identifier Type Code_46,Other Provider Identifier State_46,Other Provider Identifier Issuer_46,Other Provider Identifier_47,Other Provider Identifier Type Code_47,Other Provider Identifier State_47,Other Provider Identifier Issuer_47,Other Provider Identifier_48,Other Provider Identifier Type Code_48,Other Provider Identifier State_48,Other Provider Identifier Issuer_48,Other Provider Identifier_49,Other Provider Identifier Type Code_49,Other Provider Identifier State_49,Other Provider Identifier Issuer_49,Other Provider Identifier_50,Other Provider Identifier Type Code_50,Other Provider Identifier State_50,Other Provider Identifier Issuer_50,Is Sole Proprietor,Is Organization Subpart,Parent Organization LBN,Parent Organization TIN,Authorized Official Name Prefix Text,Authorized Official Name Suffix Text,Authorized Official Credential Text,Healthcare Provider Taxonomy Group_1,Healthcare Provider Taxonomy Group_2,Healthcare Provider Taxonomy Group_3,Healthcare Provider Taxonomy Group_4,Healthcare Provider Taxonomy Group_5,Healthcare Provider Taxonomy Group_6,Healthcare Provider Taxonomy Group_7,Healthcare Provider Taxonomy Group_8,Healthcare Provider Taxonomy Group_9,Healthcare Provider Taxonomy Group_10,Healthcare Provider Taxonomy Group_11,Healthcare Provider Taxonomy Group_12,Healthcare Provider Taxonomy Group_13,Healthcare Provider Taxonomy Group_14,Healthcare Provider Taxonomy Group_15,Certification Date
0,1215930367,1,NaN,NaN,NaN,GRESSOT,LAURENT,NaN,DR.,NaN,M.D.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17323 RED OAK DR,NaN,HOUSTON,TX,770901243,US,2.814405e+09,2.814406e+09,17323 RED OAK DR,NaN,HOUSTON,TX,770901243,US,2814405006.0,2.814406e+09,05/23/2005,11/25/2014,NaN,NaN,NaN,M,NaN,NaN,NaN,NaN,NaN,174400000X,H6257,TX,N,207RH0003X,H6257,TX,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1750384806,1,NaN,NaN,NaN,BISBEE,ROBERT,NaN,DR.,NaN,MD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5219 CITY BANK PKWY STE 214,NaN,LUBBOCK,TX,794073537,US,8.067810e+09,8.067820e+09,808 JOLIET AVE UNIT 120,NaN,LUBBOCK,TX,794151148,US,8067610540.0,8.067610e+09,05/23/2005,03/10/2017,NaN,NaN,NaN,M,NaN,NaN,NaN,NaN,NaN,207R00000X,J8461,TX,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1619970662,1,NaN,NaN,NaN,FRIEDMAN,LISA,AMY,MRS.,NaN,"RN, MSN, CPNP",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,315 N SAN SABA,SUITE 1135,SAN ANTONIO,TX,782073154,US,2.107042e+09,NaN,333 N SANTA ROSA,NaN,SAN ANTONIO,TX,782073108,US,2107042190.0,NaN,05/23/2005,11/19/2020,NaN,NaN,NaN,F,NaN,NaN,NaN,NaN,NaN,363LP0200X,662780,TX,N,363LP0200X,AP111980,TX,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/19/2020

In [7]:
df.columns.to_list()

['NPI',
 'Entity Type Code',
 'Replacement NPI',
 'Employer Identification Number (EIN)',
 'Provider Organization Name (Legal Business Name)',
 'Provider Last Name (Legal Name)',
 'Provider First Name',
 'Provider Middle Name',
 'Provider Name Prefix Text',
 'Provider Name Suffix Text',
 'Provider Credential Text',
 'Provider Other Organization Name',
 'Provider Other Organization Name Type Code',
 'Provider Other Last Name',
 'Provider Other First Name',
 'Provider Other Middle Name',
 'Provider Other Name Prefix Text',
 'Provider Other Name Suffix Text',
 'Provider Other Credential Text',
 'Provider Other Last Name Type Code',
 'Provider First Line Business Mailing Address',
 'Provider Second Line Business Mailing Address',
 'Provider Business Mailing Address City Name',
 'Provider Business Mailing Address State Name',
 'Provider Business Mailing Address Postal Code',
 'Provider Business Mailing Address Country Code (If outside U.S.)',
 'Provider Business Mailing Address Telephone Number',
 'Provider Business Mailing Address Fax Number',
 'Provider First Line Business Practice Location Address',
 'Provider Second Line Business Practice Location Address',
 'Provider Business Practice Location Address City Name',
 'Provider Business Practice Location Address State Name',
 'Provider Business Practice Location Address Postal Code',
 'Provider Business Practice Location Address Country Code (If outside U.S.)',
 'Provider Business Practice Location Address Telephone Number',
 'Provider Business Practice Location Address Fax Number',
 'Provider Enumeration Date',
 'Last Update Date',
 'NPI Deactivation Reason Code',
 'NPI Deactivation Date',
 'NPI Reactivation Date',
 'Provider Sex Code',
 'Authorized Official Last Name',
 'Authorized Official First Name',
 'Authorized Official Middle Name',
 'Authorized Official Title or Position',
 'Authorized Official Telephone Number',
 'Healthcare Provider Taxonomy Code_1',
 'Provider License Number_1',
 'Provider License Number State Code_1',
 'Healthcare Provider Primary Taxonomy Switch_1',
 'Healthcare Provider Taxonomy Code_2',
 'Provider License Number_2',
 'Provider License Number State Code_2',
 'Healthcare Provider Primary Taxonomy Switch_2',
 'Healthcare Provider Taxonomy Code_3',
 'Provider License Number_3',
 'Provider License Number State Code_3',
 'Healthcare Provider Primary Taxonomy Switch_3',
 'Healthcare Provider Taxonomy Code_4',
 'Provider License Number_4',
 'Provider License Number State Code_4',
 'Healthcare Provider Primary Taxonomy Switch_4',
 'Healthcare Provider Taxonomy Code_5',
 'Provider License Number_5',
 'Provider License Number State Code_5',
 'Healthcare Provider Primary Taxonomy Switch_5',
 'Healthcare Provider Taxonomy Code_6',
 'Provider License Number_6',
 'Provider License Number State Code_6',
 'Healthcare Provider Primary Taxonomy Switch_6',
 'Healthcare Provider Taxonomy Code_7',
 'Provider License Number_7',
 'Provider License Number State Code_7',
 'Healthcare Provider Primary Taxonomy Switch_7',
 'Healthcare Provider Taxonomy Code_8',
 'Provider License Number_8',
 'Provider License Number State Code_8',
 'Healthcare Provider Primary Taxonomy Switch_8',
 'Healthcare Provider Taxonomy Code_9',
 'Provider License Number_9',
 'Provider License Number State Code_9',
 'Healthcare Provider Primary Taxonomy Switch_9',
 'Healthcare Provider Taxonomy Code_10',
 'Provider License Number_10',
 'Provider License Number State Code_10',
 'Healthcare Provider Primary Taxonomy Switch_10',
 'Healthcare Provider Taxonomy Code_11',
 'Provider License Number_11',
 'Provider License Number State Code_11',
 'Healthcare Provider Primary Taxonomy Switch_11',
 'Healthcare Provider Taxonomy Code_12',
 'Provider License Number_12',
 'Provider License Number State Code_12',
 'Healthcare Provider Primary Taxonomy Switch_12',
 'Healthcare Provider Taxonomy Code_13',
 'Provider License Number_13',
 'Provider License Number State Code_13',
 'Healthcare Provider Primary Taxonomy Switch_13',
 'Healthcare Provider Taxonomy Code_14',
 'Provider License Number_14',
 'Provider License Number State Code_14',
 'Healthcare Provider Primary Taxonomy Switch_14',
 'Healthcare Provider Taxonomy Code_15',
 'Provider License Number_15',
 'Provider License Number State Code_15',
 'Healthcare Provider Primary Taxonomy Switch_15',
 'Other Provider Identifier_1',
 'Other Provider Identifier Type Code_1',
 'Other Provider Identifier State_1',
 'Other Provider Identifier Issuer_1',
 'Other Provider Identifier_2',
 'Other Provider Identifier Type Code_2',
 'Other Provider Identifier State_2',
 'Other Provider Identifier Issuer_2',
 'Other Provider Identifier_3',
 'Other Provider Identifier Type Code_3',
 'Other Provider Identifier State_3',
 'Other Provider Identifier Issuer_3',
 'Other Provider Identifier_4',
 'Other Provider Identifier Type Code_4',
 'Other Provider Identifier State_4',
 'Other Provider Identifier Issuer_4',
 'Other Provider Identifier_5',
 'Other Provider Identifier Type Code_5',
 'Other Provider Identifier State_5',
 'Other Provider Identifier Issuer_5',
 'Other Provider Identifier_6',
 'Other Provider Identifier Type Code_6',
 'Other Provider Identifier State_6',
 'Other Provider Identifier Issuer_6',
 'Other Provider Identifier_7',
 'Other Provider Identifier Type Code_7',
 'Other Provider Identifier State_7',
 'Other Provider Identifier Issuer_7',
 'Other Provider Identifier_8',
 'Other Provider Identifier Type Code_8',
 'Other Provider Identifier State_8',
 'Other Provider Identifier Issuer_8',
 'Other Provider Identifier_9',
 'Other Provider Identifier Type Code_9',
 'Other Provider Identifier State_9',
 'Other Provider Identifier Issuer_9',
 'Other Provider Identifier_10',
 'Other Provider Identifier Type Code_10',
 'Other Provider Identifier State_10',
 'Other Provider Identifier Issuer_10',
 'Other Provider Identifier_11',
 'Other Provider Identifier Type Code_11',
 'Other Provider Identifier State_11',
 'Other Provider Identifier Issuer_11',
 'Other Provider Identifier_12',
 'Other Provider Identifier Type Code_12',
 'Other Provider Identifier State_12',
 'Other Provider Identifier Issuer_12',
 'Other Provider Identifier_13',
 'Other Provider Identifier Type Code_13',
 'Other Provider Identifier State_13',
 'Other Provider Identifier Issuer_13',
 'Other Provider Identifier_14',
 'Other Provider Identifier Type Code_14',
 'Other Provider Identifier State_14',
 'Other Provider Identifier Issuer_14',
 'Other Provider Identifier_15',
 'Other Provider Identifier Type Code_15',
 'Other Provider Identifier State_15',
 'Other Provider Identifier Issuer_15',
 'Other Provider Identifier_16',
 'Other Provider Identifier Type Code_16',
 'Other Provider Identifier State_16',
 'Other Provider Identifier Issuer_16',
 'Other Provider Identifier_17',
 'Other Provider Identifier Type Code_17',
 'Other Provider Identifier State_17',
 'Other Provider Identifier Issuer_17',
 'Other Provider Identifier_18',
 'Other Provider Identifier Type Code_18',
 'Other Provider Identifier State_18',
 'Other Provider Identifier Issuer_18',
 'Other Provider Identifier_19',
 'Other Provider Identifier Type Code_19',
 'Other Provider Identifier State_19',
 'Other Provider Identifier Issuer_19',
 'Other Provider Identifier_20',
 'Other Provider Identifier Type Code_20',
 'Other Provider Identifier State_20',
 'Other Provider Identifier Issuer_20',
 'Other Provider Identifier_21',
 'Other Provider Identifier Type Code_21',
 'Other Provider Identifier State_21',
 'Other Provider Identifier Issuer_21',
 'Other Provider Identifier_22',
 'Other Provider Identifier Type Code_22',
 'Other Provider Identifier State_22',
 'Other Provider Identifier Issuer_22',
 'Other Provider Identifier_23',
 'Other Provider Identifier Type Code_23',
 'Other Provider Identifier State_23',
 'Other Provider Identifier Issuer_23',
 'Other Provider Identifier_24',
 'Other Provider Identifier Type Code_24',
 'Other Provider Identifier State_24',
 'Other Provider Identifier Issuer_24',
 'Other Provider Identifier_25',
 'Other Provider Identifier Type Code_25',
 'Other Provider Identifier State_25',
 'Other Provider Identifier Issuer_25',
 'Other Provider Identifier_26',
 'Other Provider Identifier Type Code_26',
 'Other Provider Identifier State_26',
 'Other Provider Identifier Issuer_26',
 'Other Provider Identifier_27',
 'Other Provider Identifier Type Code_27',
 'Other Provider Identifier State_27',
 'Other Provider Identifier Issuer_27',
 'Other Provider Identifier_28',
 'Other Provider Identifier Type Code_28',
 'Other Provider Identifier State_28',
 'Other Provider Identifier Issuer_28',
 'Other Provider Identifier_29',
 'Other Provider Identifier Type Code_29',
 'Other Provider Identifier State_29',
 'Other Provider Identifier Issuer_29',
 'Other Provider Identifier_30',
 'Other Provider Identifier Type Code_30',
 'Other Provider Identifier State_30',
 'Other Provider Identifier Issuer_30',
 'Other Provider Identifier_31',
 'Other Provider Identifier Type Code_31',
 'Other Provider Identifier State_31',
 'Other Provider Identifier Issuer_31',
 'Other Provider Identifier_32',
 'Other Provider Identifier Type Code_32',
 'Other Provider Identifier State_32',
 'Other Provider Identifier Issuer_32',
 'Other Provider Identifier_33',
 'Other Provider Identifier Type Code_33',
 'Other Provider Identifier State_33',
 'Other Provider Identifier Issuer_33',
 'Other Provider Identifier_34',
 'Other Provider Identifier Type Code_34',
 'Other Provider Identifier State_34',
 'Other Provider Identifier Issuer_34',
 'Other Provider Identifier_35',
 'Other Provider Identifier Type Code_35',
 'Other Provider Identifier State_35',
 'Other Provider Identifier Issuer_35',
 'Other Provider Identifier_36',
 'Other Provider Identifier Type Code_36',
 'Other Provider Identifier State_36',
 'Other Provider Identifier Issuer_36',
 'Other Provider Identifier_37',
 'Other Provider Identifier Type Code_37',
 'Other Provider Identifier State_37',
 'Other Provider Identifier Issuer_37',
 'Other Provider Identifier_38',
 'Other Provider Identifier Type Code_38',
 'Other Provider Identifier State_38',
 'Other Provider Identifier Issuer_38',
 'Other Provider Identifier_39',
 'Other Provider Identifier Type Code_39',
 'Other Provider Identifier State_39',
 'Other Provider Identifier Issuer_39',
 'Other Provider Identifier_40',
 'Other Provider Identifier Type Code_40',
 'Other Provider Identifier State_40',
 'Other Provider Identifier Issuer_40',
 'Other Provider Identifier_41',
 'Other Provider Identifier Type Code_41',
 'Other Provider Identifier State_41',
 'Other Provider Identifier Issuer_41',
 'Other Provider Identifier_42',
 'Other Provider Identifier Type Code_42',
 'Other Provider Identifier State_42',
 'Other Provider Identifier Issuer_42',
 'Other Provider Identifier_43',
 'Other Provider Identifier Type Code_43',
 'Other Provider Identifier State_43',
 'Other Provider Identifier Issuer_43',
 'Other Provider Identifier_44',
 'Other Provider Identifier Type Code_44',
 'Other Provider Identifier State_44',
 'Other Provider Identifier Issuer_44',
 'Other Provider Identifier_45',
 'Other Provider Identifier Type Code_45',
 'Other Provider Identifier State_45',
 'Other Provider Identifier Issuer_45',
 'Other Provider Identifier_46',
 'Other Provider Identifier Type Code_46',
 'Other Provider Identifier State_46',
 'Other Provider Identifier Issuer_46',
 'Other Provider Identifier_47',
 'Other Provider Identifier Type Code_47',
 'Other Provider Identifier State_47',
 'Other Provider Identifier Issuer_47',
 'Other Provider Identifier_48',
 'Other Provider Identifier Type Code_48',
 'Other Provider Identifier State_48',
 'Other Provider Identifier Issuer_48',
 'Other Provider Identifier_49',
 'Other Provider Identifier Type Code_49',
 'Other Provider Identifier State_49',
 'Other Provider Identifier Issuer_49',
 'Other Provider Identifier_50',
 'Other Provider Identifier Type Code_50',
 'Other Provider Identifier State_50',
 'Other Provider Identifier Issuer_50',
 'Is Sole Proprietor',
 'Is Organization Subpart',
 'Parent Organization LBN',
 'Parent Organization TIN',
 'Authorized Official Name Prefix Text',
 'Authorized Official Name Suffix Text',
 'Authorized Official Credential Text',
 'Healthcare Provider Taxonomy Group_1',
 'Healthcare Provider Taxonomy Group_2',
 'Healthcare Provider Taxonomy Group_3',
 'Healthcare Provider Taxonomy Group_4',
 'Healthcare Provider Taxonomy Group_5',
 'Healthcare Provider Taxonomy Group_6',
 'Healthcare Provider Taxonomy Group_7',
 'Healthcare Provider Taxonomy Group_8',
 'Healthcare Provider Taxonomy Group_9',
 'Healthcare Provider Taxonomy Group_10',
 'Healthcare Provider Taxonomy Group_11',
 'Healthcare Provider Taxonomy Group_12',
 'Healthcare Provider Taxonomy Group_13',
 'Healthcare Provider Taxonomy Group_14',
 'Healthcare Provider Taxonomy Group_15',
 'Certification Date']

In [5]:
df.shape

(563863, 330)

In [6]:
missing_percentage = df.isnull().mean() * 100
print(missing_percentage)

NPI                                                  0.000000
Entity Type Code                                     0.000000
Replacement NPI                                     99.998227
Employer Identification Number (EIN)                71.857348
Provider Organization Name (Legal Business Name)    71.857880
                                                      ...
Healthcare Provider Taxonomy Group_12               99.940411
Healthcare Provider Taxonomy Group_13               99.953357
Healthcare Provider Taxonomy Group_14               99.964708
Healthcare Provider Taxonomy Group_15               99.975881
Certification Date                                  48.870914
Length: 330, dtype: float64

In [7]:
df.dtypes

NPI                                                   int64
Entity Type Code                                      int64
Replacement NPI                                     float64
Employer Identification Number (EIN)                 object
Provider Organization Name (Legal Business Name)     object
                                                     ...
Healthcare Provider Taxonomy Group_12                object
Healthcare Provider Taxonomy Group_13                object
Healthcare Provider Taxonomy Group_14                object
Healthcare Provider Taxonomy Group_15                object
Certification Date                                   object
Length: 330, dtype: object

In [8]:
# Individual providers (Entity Type Code = 1)
individual_providers = df[df["Entity Type Code"] == 1]

# Organization providers (Entity Type Code = 2)
organization_providers = df[df["Entity Type Code"] == 2]

In [9]:
individual_providers.shape

(405177, 330)

In [10]:
organization_providers.shape

(158686, 330)

In [11]:
base_columns = [
    "NPI",
    "Entity Type Code",
    "Provider Organization Name (Legal Business Name)",
    "Provider Last Name (Legal Name)",
    "Provider First Name",
    "Provider Business Practice Location Address City Name",
    "Provider Business Practice Location Address State Name",
    "Provider Business Practice Location Address Postal Code",
    "Provider First Line Business Practice Location Address",
    "Provider Business Practice Location Address Telephone Number",
]

# Step 2: Flatten taxonomy fields into two new features
def extract_taxonomy_fields(row):
    taxonomy_codes = []
    primary_code = None
    for i in range(1, 16):
        code = row.get(f"Healthcare Provider Taxonomy Code_{i}")
        primary_switch = row.get(f"Healthcare Provider Primary Taxonomy Switch_{i}")
        if pd.notna(code):
            taxonomy_codes.append(code)
            if primary_switch == "Y":
                primary_code = code
    return pd.Series({
        "Taxonomy Codes": taxonomy_codes,
        "Primary Taxonomy Code": primary_code
    })

In [12]:
# Step 3: Apply transformation and merge with base columns
taxonomy_df = df.apply(extract_taxonomy_fields, axis=1)
df_filtered = pd.concat([df[base_columns], taxonomy_df], axis=1)

In [13]:
df_filtered["Provider Business Practice Location Address Telephone Number"] = df_filtered["Provider Business Practice Location Address Telephone Number"].apply(lambda x: x.split(".")[0])

In [14]:
df_filtered.head()

,NPI,Entity Type Code,Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Business Practice Location Address City Name,Provider Business Practice Location Address State Name,Provider Business Practice Location Address Postal Code,Provider First Line Business Practice Location Address,Provider Business Practice Location Address Telephone Number,Taxonomy Codes,Primary Taxonomy Code
0,1215930367,1,NaN,GRESSOT,LAURENT,HOUSTON,TX,770901243,17323 RED OAK DR,2814405006,"[174400000X, 207RH0003X]",207RH0003X
1,1750384806,1,NaN,BISBEE,ROBERT,LUBBOCK,TX,794151148,808 JOLIET AVE UNIT 120,8067610540,[207R00000X],207R00000X
2,1619970662,1,NaN,FRIEDMAN,LISA,SAN ANTONIO,TX,782073108,333 N SANTA ROSA,2107042190,"[363LP0200X, 363LP0200X]",363LP0200X
3,1598768541,1,NaN,ARENAS,BERTHA,SAN ANTONIO,TX,782151201,1702 N ALAMO ST,2102241823,[363LF0000X],363LF0000X
4,1649273681,1,NaN,RENOUF,ROSE ANN,FORT WORTH,TX,761026026,1401 HENDERSON ST,8173327664,[367500000X],367500000X

In [15]:
df_filtered.isnull().mean() * 100

NPI                                                              0.000000
Entity Type Code                                                 0.000000
Provider Organization Name (Legal Business Name)                71.857880
Provider Last Name (Legal Name)                                 28.144603
Provider First Name                                             28.143716
Provider Business Practice Location Address City Name            0.000000
Provider Business Practice Location Address State Name           0.000355
Provider Business Practice Location Address Postal Code          0.000000
Provider First Line Business Practice Location Address           0.000000
Provider Business Practice Location Address Telephone Number     0.000000
Taxonomy Codes                                                   0.000000
Primary Taxonomy Code                                            0.455430
dtype: float64

In [16]:
df_filtered.dtypes

NPI                                                              int64
Entity Type Code                                                 int64
Provider Organization Name (Legal Business Name)                object
Provider Last Name (Legal Name)                                 object
Provider First Name                                             object
Provider Business Practice Location Address City Name           object
Provider Business Practice Location Address State Name          object
Provider Business Practice Location Address Postal Code         object
Provider First Line Business Practice Location Address          object
Provider Business Practice Location Address Telephone Number    object
Taxonomy Codes                                                  object
Primary Taxonomy Code                                           object
dtype: object

In [17]:
df_filtered.groupby('Entity Type Code')['Entity Type Code'].count()

Entity Type Code
1    405177
2    158686
Name: Entity Type Code, dtype: int64

In [18]:
df_filtered[df_filtered['Entity Type Code'] == 2].head()

,NPI,Entity Type Code,Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Business Practice Location Address City Name,Provider Business Practice Location Address State Name,Provider Business Practice Location Address Postal Code,Provider First Line Business Practice Location Address,Provider Business Practice Location Address Telephone Number,Taxonomy Codes,Primary Taxonomy Code
7,1205839230,2,"MERCY EMS, LLC",NaN,NaN,ADDISON,TX,750013282,15401 ADDISON RD,9727889401,[3416L0300X],3416L0300X
8,1831192863,2,MONCRIEF CANCER CENTER,NaN,NaN,FORT WORTH,TX,761044110,1450 8TH AVE,8179237393,"[261QX0203X, 261QX0203X]",261QX0203X
17,1013910058,2,"WESTHEIMER VISION ASSOCIATES, PC",NaN,NaN,HOUSTON,TX,770423107,10260 WESTHEIMER RD,7137813517,"[152W00000X, 152W00000X, 152W00000X, 152W00000...",152W00000X
24,1093718025,2,YODORINCMISSIONPLAZAPHARMACY,NaN,NaN,MISSION,TX,785748606,RR 8 BOX 3311,9565830044,"[332B00000X, 333600000X]",None
31,1063415008,2,ARLINGTON MEDICAL IMAGING LLC,NaN,NaN,ARLINGTON,TX,760152902,3025 MATLOCK RD,8174676099,"[293D00000X, 2085R0202X]",2085R0202X

In [19]:
df_filtered[df_filtered['Entity Type Code'] == 1].head()

,NPI,Entity Type Code,Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Business Practice Location Address City Name,Provider Business Practice Location Address State Name,Provider Business Practice Location Address Postal Code,Provider First Line Business Practice Location Address,Provider Business Practice Location Address Telephone Number,Taxonomy Codes,Primary Taxonomy Code
0,1215930367,1,NaN,GRESSOT,LAURENT,HOUSTON,TX,770901243,17323 RED OAK DR,2814405006,"[174400000X, 207RH0003X]",207RH0003X
1,1750384806,1,NaN,BISBEE,ROBERT,LUBBOCK,TX,794151148,808 JOLIET AVE UNIT 120,8067610540,[207R00000X],207R00000X
2,1619970662,1,NaN,FRIEDMAN,LISA,SAN ANTONIO,TX,782073108,333 N SANTA ROSA,2107042190,"[363LP0200X, 363LP0200X]",363LP0200X
3,1598768541,1,NaN,ARENAS,BERTHA,SAN ANTONIO,TX,782151201,1702 N ALAMO ST,2102241823,[363LF0000X],363LF0000X
4,1649273681,1,NaN,RENOUF,ROSE ANN,FORT WORTH,TX,761026026,1401 HENDERSON ST,8173327664,[367500000X],367500000X

In [20]:
df_filtered.groupby('Primary Taxonomy Code')['Primary Taxonomy Code'].count()

Primary Taxonomy Code
101200000X        8
101Y00000X     3568
101YA0400X     2406
101YM0800X    10142
101YP1600X      133
              ...
385HR2055X        3
385HR2060X       53
385HR2065X       11
390200000X    17179
405300000X       18
Name: Primary Taxonomy Code, Length: 830, dtype: int64

In [21]:
df_filtered.columns

Index(['NPI', 'Entity Type Code',
       'Provider Organization Name (Legal Business Name)',
       'Provider Last Name (Legal Name)', 'Provider First Name',
       'Provider Business Practice Location Address City Name',
       'Provider Business Practice Location Address State Name',
       'Provider Business Practice Location Address Postal Code',
       'Provider First Line Business Practice Location Address',
       'Provider Business Practice Location Address Telephone Number',
       'Taxonomy Codes', 'Primary Taxonomy Code'],
      dtype='object')

In [22]:
df_filtered.dtypes

NPI                                                              int64
Entity Type Code                                                 int64
Provider Organization Name (Legal Business Name)                object
Provider Last Name (Legal Name)                                 object
Provider First Name                                             object
Provider Business Practice Location Address City Name           object
Provider Business Practice Location Address State Name          object
Provider Business Practice Location Address Postal Code         object
Provider First Line Business Practice Location Address          object
Provider Business Practice Location Address Telephone Number    object
Taxonomy Codes                                                  object
Primary Taxonomy Code                                           object
dtype: object

In [23]:
df_filtered['Entity Type Code'] = df_filtered['Entity Type Code'].replace({1: 'Individual', 2: 'Organization'})

In [24]:
df_filtered.groupby('Entity Type Code')['Entity Type Code'].count()

Entity Type Code
Individual      405177
Organization    158686
Name: Entity Type Code, dtype: int64

In [25]:
column_rename_map = {
    "NPI": "npi_number",
    "Entity Type Code": "entity_type",
    "Provider Organization Name (Legal Business Name)": "provider_org_name_legal",
    "Provider Last Name (Legal Name)": "provider_last_name_legal",
    "Provider First Name": "provider_first_name",
    "Provider Business Practice Location Address City Name": "practice_city_name",
    "Provider Business Practice Location Address State Name": "practice_state_name",
    "Provider Business Practice Location Address Postal Code": "practice_postal_code",
    "Provider First Line Business Practice Location Address": "practice_street_address",
    "Provider Business Practice Location Address Telephone Number": "practice_phone_number",
    "Taxonomy Codes": "taxonomy_codes_list",
    "Primary Taxonomy Code": "primary_taxonomy_code"
}

renamed_df = df_filtered.rename(columns=column_rename_map)

In [26]:
renamed_df.head()

,npi_number,entity_type,provider_org_name_legal,provider_last_name_legal,provider_first_name,practice_city_name,practice_state_name,practice_postal_code,practice_street_address,practice_phone_number,taxonomy_codes_list,primary_taxonomy_code
0,1215930367,Individual,NaN,GRESSOT,LAURENT,HOUSTON,TX,770901243,17323 RED OAK DR,2814405006,"[174400000X, 207RH0003X]",207RH0003X
1,1750384806,Individual,NaN,BISBEE,ROBERT,LUBBOCK,TX,794151148,808 JOLIET AVE UNIT 120,8067610540,[207R00000X],207R00000X
2,1619970662,Individual,NaN,FRIEDMAN,LISA,SAN ANTONIO,TX,782073108,333 N SANTA ROSA,2107042190,"[363LP0200X, 363LP0200X]",363LP0200X
3,1598768541,Individual,NaN,ARENAS,BERTHA,SAN ANTONIO,TX,782151201,1702 N ALAMO ST,2102241823,[363LF0000X],363LF0000X
4,1649273681,Individual,NaN,RENOUF,ROSE ANN,FORT WORTH,TX,761026026,1401 HENDERSON ST,8173327664,[367500000X],367500000X

In [27]:
renamed_df.groupby('practice_city_name')['practice_city_name'].count()

practice_city_name
77354                      1
ABBEVILLE                  2
ABBOTT                     4
ABERDEEN                   6
ABERDEEN PROVING GROUND    1
                          ..
ZEPHYRHILLS                3
ZIMMERMAN                  1
ZION                       1
ZIONSVILLE                 1
ZUNI                       1
Name: practice_city_name, Length: 5255, dtype: int64

In [28]:
renamed_df.columns

Index(['npi_number', 'entity_type', 'provider_org_name_legal',
       'provider_last_name_legal', 'provider_first_name', 'practice_city_name',
       'practice_state_name', 'practice_postal_code',
       'practice_street_address', 'practice_phone_number',
       'taxonomy_codes_list', 'primary_taxonomy_code'],
      dtype='object')

In [29]:
# Load NUCC taxonomy reference data
taxonomy_df = pd.read_csv("../data/nucc_taxonomy_250.csv")
taxonomy_df.head()

,Code,Grouping,Classification,Specialization,Definition,Notes,Display Name,Section
0,193200000X,Group,Multi-Specialty,NaN,A business group of one or more individual pra...,[7/1/2003: new],Multi-Specialty Group,Individual
1,193400000X,Group,Single Specialty,NaN,A business group of one or more individual pra...,[7/1/2003: new],Single Specialty Group,Individual
2,207K00000X,Allopathic & Osteopathic Physicians,Allergy & Immunology,NaN,An allergist-immunologist is trained in evalua...,"Source: American Board of Medical Specialties,...",Allergy & Immunology Physician,Individual
3,207KA0200X,Allopathic & Osteopathic Physicians,Allergy & Immunology,Allergy,"A physician who specializes in the diagnosis, ...",Source: National Uniform Claim Committee,Allergy Physician,Individual
4,207KI0005X,Allopathic & Osteopathic Physicians,Allergy & Immunology,Clinical & Laboratory Immunology,An allergy and immunology physician who specia...,"Source: National Uniform Claim Committee, 2022...",Clinical & Laboratory Immunology (Allergy & Im...,Individual

In [30]:
# Create human-readable description for each taxonomy code
def build_taxonomy_description(row):
    if pd.notna(row["Specialization"]):
        return f"{row['Classification']} - {row['Specialization']}"
    else:
        return row["Classification"]

In [31]:
taxonomy_df["taxonomy_description"] = taxonomy_df.apply(build_taxonomy_description, axis=1)

In [32]:
taxonomy_df.head()

,Code,Grouping,Classification,Specialization,Definition,Notes,Display Name,Section,taxonomy_description
0,193200000X,Group,Multi-Specialty,NaN,A business group of one or more individual pra...,[7/1/2003: new],Multi-Specialty Group,Individual,Multi-Specialty
1,193400000X,Group,Single Specialty,NaN,A business group of one or more individual pra...,[7/1/2003: new],Single Specialty Group,Individual,Single Specialty
2,207K00000X,Allopathic & Osteopathic Physicians,Allergy & Immunology,NaN,An allergist-immunologist is trained in evalua...,"Source: American Board of Medical Specialties,...",Allergy & Immunology Physician,Individual,Allergy & Immunology
3,207KA0200X,Allopathic & Osteopathic Physicians,Allergy & Immunology,Allergy,"A physician who specializes in the diagnosis, ...",Source: National Uniform Claim Committee,Allergy Physician,Individual,Allergy & Immunology - Allergy
4,207KI0005X,Allopathic & Osteopathic Physicians,Allergy & Immunology,Clinical & Laboratory Immunology,An allergy and immunology physician who specia...,"Source: National Uniform Claim Committee, 2022...",Clinical & Laboratory Immunology (Allergy & Im...,Individual,Allergy & Immunology - Clinical & Laboratory I...

In [33]:
# Create the mapping dictionary: {code: description}
taxonomy_map = dict(zip(taxonomy_df["Code"], taxonomy_df["taxonomy_description"]))

In [35]:
# taxonomy_map

In [36]:
# Convert stringified list to list (if needed)
renamed_df["taxonomy_codes_list"] = renamed_df["taxonomy_codes_list"].apply(
    lambda x: eval(x) if isinstance(x, str) else x
)

In [37]:
renamed_df.head()

,npi_number,entity_type,provider_org_name_legal,provider_last_name_legal,provider_first_name,practice_city_name,practice_state_name,practice_postal_code,practice_street_address,practice_phone_number,taxonomy_codes_list,primary_taxonomy_code
0,1215930367,Individual,NaN,GRESSOT,LAURENT,HOUSTON,TX,770901243,17323 RED OAK DR,2814405006,"[174400000X, 207RH0003X]",207RH0003X
1,1750384806,Individual,NaN,BISBEE,ROBERT,LUBBOCK,TX,794151148,808 JOLIET AVE UNIT 120,8067610540,[207R00000X],207R00000X
2,1619970662,Individual,NaN,FRIEDMAN,LISA,SAN ANTONIO,TX,782073108,333 N SANTA ROSA,2107042190,"[363LP0200X, 363LP0200X]",363LP0200X
3,1598768541,Individual,NaN,ARENAS,BERTHA,SAN ANTONIO,TX,782151201,1702 N ALAMO ST,2102241823,[363LF0000X],363LF0000X
4,1649273681,Individual,NaN,RENOUF,ROSE ANN,FORT WORTH,TX,761026026,1401 HENDERSON ST,8173327664,[367500000X],367500000X

In [38]:
# Map taxonomy_codes_list to description list
def map_taxonomy_list(codes):
    return [taxonomy_map.get(code, code) for code in codes]

In [39]:
renamed_df["taxonomy_descriptions_list"] = renamed_df["taxonomy_codes_list"].apply(map_taxonomy_list)

In [40]:
renamed_df.head()

,npi_number,entity_type,provider_org_name_legal,provider_last_name_legal,provider_first_name,practice_city_name,practice_state_name,practice_postal_code,practice_street_address,practice_phone_number,taxonomy_codes_list,primary_taxonomy_code,taxonomy_descriptions_list
0,1215930367,Individual,NaN,GRESSOT,LAURENT,HOUSTON,TX,770901243,17323 RED OAK DR,2814405006,"[174400000X, 207RH0003X]",207RH0003X,"[Specialist, Internal Medicine - Hematology & ..."
1,1750384806,Individual,NaN,BISBEE,ROBERT,LUBBOCK,TX,794151148,808 JOLIET AVE UNIT 120,8067610540,[207R00000X],207R00000X,[Internal Medicine]
2,1619970662,Individual,NaN,FRIEDMAN,LISA,SAN ANTONIO,TX,782073108,333 N SANTA ROSA,2107042190,"[363LP0200X, 363LP0200X]",363LP0200X,"[Nurse Practitioner - Pediatrics, Nurse Practi..."
3,1598768541,Individual,NaN,ARENAS,BERTHA,SAN ANTONIO,TX,782151201,1702 N ALAMO ST,2102241823,[363LF0000X],363LF0000X,[Nurse Practitioner - Family]
4,1649273681,Individual,NaN,RENOUF,ROSE ANN,FORT WORTH,TX,761026026,1401 HENDERSON ST,8173327664,[367500000X],367500000X,"[Nurse Anesthetist, Certified Registered]"

In [41]:
# Map primary_taxonomy_code to description
renamed_df["primary_taxonomy_description"] = renamed_df["primary_taxonomy_code"].map(taxonomy_map)

In [42]:
renamed_df.head()

,npi_number,entity_type,provider_org_name_legal,provider_last_name_legal,provider_first_name,practice_city_name,practice_state_name,practice_postal_code,practice_street_address,practice_phone_number,taxonomy_codes_list,primary_taxonomy_code,taxonomy_descriptions_list,primary_taxonomy_description
0,1215930367,Individual,NaN,GRESSOT,LAURENT,HOUSTON,TX,770901243,17323 RED OAK DR,2814405006,"[174400000X, 207RH0003X]",207RH0003X,"[Specialist, Internal Medicine - Hematology & ...",Internal Medicine - Hematology & Oncology
1,1750384806,Individual,NaN,BISBEE,ROBERT,LUBBOCK,TX,794151148,808 JOLIET AVE UNIT 120,8067610540,[207R00000X],207R00000X,[Internal Medicine],Internal Medicine
2,1619970662,Individual,NaN,FRIEDMAN,LISA,SAN ANTONIO,TX,782073108,333 N SANTA ROSA,2107042190,"[363LP0200X, 363LP0200X]",363LP0200X,"[Nurse Practitioner - Pediatrics, Nurse Practi...",Nurse Practitioner - Pediatrics
3,1598768541,Individual,NaN,ARENAS,BERTHA,SAN ANTONIO,TX,782151201,1702 N ALAMO ST,2102241823,[363LF0000X],363LF0000X,[Nurse Practitioner - Family],Nurse Practitioner - Family
4,1649273681,Individual,NaN,RENOUF,ROSE ANN,FORT WORTH,TX,761026026,1401 HENDERSON ST,8173327664,[367500000X],367500000X,"[Nurse Anesthetist, Certified Registered]","Nurse Anesthetist, Certified Registered"

In [44]:
renamed_df[renamed_df['entity_type'] == 'Organization'].head()

,npi_number,entity_type,provider_org_name_legal,provider_last_name_legal,provider_first_name,practice_city_name,practice_state_name,practice_postal_code,practice_street_address,practice_phone_number,taxonomy_codes_list,primary_taxonomy_code,taxonomy_descriptions_list,primary_taxonomy_description
7,1205839230,Organization,"MERCY EMS, LLC",NaN,NaN,ADDISON,TX,750013282,15401 ADDISON RD,9727889401,[3416L0300X],3416L0300X,[Ambulance - Land Transport],Ambulance - Land Transport
8,1831192863,Organization,MONCRIEF CANCER CENTER,NaN,NaN,FORT WORTH,TX,761044110,1450 8TH AVE,8179237393,"[261QX0203X, 261QX0203X]",261QX0203X,"[Clinic/Center - Oncology, Radiation, Clinic/C...","Clinic/Center - Oncology, Radiation"
17,1013910058,Organization,"WESTHEIMER VISION ASSOCIATES, PC",NaN,NaN,HOUSTON,TX,770423107,10260 WESTHEIMER RD,7137813517,"[152W00000X, 152W00000X, 152W00000X, 152W00000...",152W00000X,"[Optometrist, Optometrist, Optometrist, Optome...",Optometrist
24,1093718025,Organization,YODORINCMISSIONPLAZAPHARMACY,NaN,NaN,MISSION,TX,785748606,RR 8 BOX 3311,9565830044,"[332B00000X, 333600000X]",None,"[Durable Medical Equipment & Medical Supplies,...",NaN
31,1063415008,Organization,ARLINGTON MEDICAL IMAGING LLC,NaN,NaN,ARLINGTON,TX,760152902,3025 MATLOCK RD,8174676099,"[293D00000X, 2085R0202X]",2085R0202X,"[Physiological Laboratory, Radiology - Diagnos...",Radiology - Diagnostic Radiology

In [45]:
renamed_df.isnull().mean() * 100

npi_number                       0.000000
entity_type                      0.000000
provider_org_name_legal         71.857880
provider_last_name_legal        28.144603
provider_first_name             28.143716
practice_city_name               0.000000
practice_state_name              0.000355
practice_postal_code             0.000000
practice_street_address          0.000000
practice_phone_number            0.000000
taxonomy_codes_list              0.000000
primary_taxonomy_code            0.455430
taxonomy_descriptions_list       0.000000
primary_taxonomy_description     0.455430
dtype: float64

In [46]:
renamed_df.groupby('primary_taxonomy_description')['primary_taxonomy_description'].count()

primary_taxonomy_description
Acupuncturist                                                1334
Adult Companion                                               183
Advanced Practice Dental Therapist                              1
Advanced Practice Midwife                                     628
Allergy & Immunology                                          492
                                                             ...
Urology                                                      1206
Urology - Pediatric Urology                                    56
Urology - Urogynecology and Reconstructive Pelvic Surgery      13
Veterinarian                                                   44
Voluntary or Charitable                                       134
Name: primary_taxonomy_description, Length: 828, dtype: int64